apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-dependencies-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-dependencies-deployer
rules:
  - apiGroups: [""]
    resources: [pods, services]
    verbs: [create, delete, get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: test-dependencies-deployer
subjects:
  - kind: ServiceAccount
    name: test-dependencies-deployer
roleRef:
  kind: Role
  name: test-dependencies-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-striv-run-2
spec:
  pipelineRef:
    name: deploy-striv # We want to run this pipeline
  serviceAccountNames:
    # Tasks to set up and tear down test dependencies need to use a service account
    - taskName: deploy-test-dependencies
      serviceAccountName: test-dependencies-deployer
    - taskName: delete-test-dependencies
      serviceAccountName: test-dependencies-deployer
  workspaces:
    - # This describes how to provide the workspace that the pipeline requires
      name: striv-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
